### ISSUE TITLE
CreateFile return -5

### ISSUE THREAD

**Issue by chaohuzhang** [RileyWen/ScreenExpander#1]
I am able to install the Indirect display driver success and working,but when run ConsoleDriverApplication.exe
```
.\ConsoleDriverApplication.exe
e
Enumerate Interface Data Succeed!
Probe Interface Data Buffer Length Succeed!
Allocate Interface Data Buffer Length Succeed!
Query Interface Data Succeed! Path: \\?\root#unknown#0000#{6b06164c-8a07-4820-9139-19758f29e43e}
Error value: 5 Message: Access is denied。
Call IOCTL Failed!
n
Enumerate Interface Data Succeed!
Probe Interface Data Buffer Length Succeed!
Allocate Interface Data Buffer Length Succeed!
Query Interface Data Succeed! Path: \\?\root#unknown#0000#{6b06164c-8a07-4820-9139-19758f29e43e}
Error value: 5 Message: Access is denied。
NewMonitorTest Failed!
```

**Comment by RileyWen** [comment]
Well, it's a strange problem. My temporary solution is that after you update or install the driver, restart the Indirect Display device in Windows Device Manager.
Although I haven't searched the MSDN for the detailed reason,  I think it has something to do with the permission (may be assigned in INF file).
BTW, This project is now under development, so I haven't written the documentation on it. ConsoleDriverApplication is just used for testing purpose. It's not the real client that receives desktop image.

**Comment by RileyWen** [comment]
It's now fixed.
